/** @type {import('tailwindcss').Config} */
export default {
    // Chỉ điểm cho Tailwind biết file mô cần quét
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
              "surface-container-lowest": "#ffffff",
              "surface-container-low": "#f6f3ee",
              "surface-container-high": "#ebe8e3",
              "tertiary-fixed-dim": "#b7ccb9",
              "primary-container": "#809b77",
              "on-primary-fixed-variant": "#354d2f",
              "on-surface-variant": "#46483c",
              "surface-variant": "#e5e2dd",
              "inverse-on-surface": "#f3f0eb",
              "tertiary-container": "#849887",
              "primary-fixed": "#ceebc2",
              "secondary": "#6a5c48",
              "surface-container": "#f0ede8",
              "primary": "#4c6545",
              "inverse-surface": "#31302d",
              "surface-tint": "#4c6545",
              "tertiary-fixed": "#d3e8d5",
              "on-error": "#ffffff",
              "on-tertiary-container": "#1e3023",
              "secondary-fixed": "#f3e0c6",
              "surface-container-highest": "#e5e2dd",
              "surface-bright": "#fcf9f4",
              "on-background": "#1c1c19",
              "on-tertiary": "#ffffff",
              "on-secondary-fixed": "#231a0a",
              "on-primary-fixed": "#0a2007",
              "inverse-primary": "#b3cea7",
              "surface-dim": "#dcdad5",
              "error": "#ba1a1a",
              "surface": "#fcf9f4",
              "on-secondary-fixed-variant": "#514532",
              "outline-variant": "#c6c8b8",
              "secondary-container": "#f0ddc3",
              "primary-fixed-dim": "#b3cea7",
              "on-tertiary-fixed-variant": "#394b3d",
              "outline": "#76786b",
              "on-primary": "#ffffff",
              "secondary-fixed-dim": "#d6c4ab",
              "on-secondary": "#ffffff",
              "on-primary-container": "#1b3116",
              "error-container": "#ffdad6",
              "background": "#fcf9f4",
              "on-secondary-container": "#6e614c",
              "on-error-container": "#93000a",
              "on-surface": "#1c1c19",
              "on-tertiary-fixed": "#0e1f13",
              "tertiary": "#506354"
            },
            fontFamily: {
              "notoSerif": ["Noto Serif", "serif"],
              "manrope": ["Manrope", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
    plugins: [],
}